(ns com.tylerkindy.aoc2024.day08-test
  (:require [com.tylerkindy.aoc2024.day08 :as day08]
            [clojure.test :refer [deftest is]]))

(def example-input "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
")
(def example {:dimensions [12 12]
              :antennas {\0 #{[8 1] [5 2] [7 3] [4 4]}
                         \A #{[6 5] [8 8] [9 9]}}})

(deftest parse-input
  (is (= (day08/parse-input example-input)
         example)))
